name: Linting
permissions:
  contents: read
on:
  pull_request:
    branches:
      - feature/DESCW-3091_node-update
  workflow_dispatch:

jobs:
  trigger:
    uses: bcgov/des-git-workflows/.github/workflows/linting.yml@main